services:
  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:userpassword@postgres_flask:5432/flaskdb
    depends_on:
      - postgres_flask
    ports:
      - "5000:5000"
      
  frontend:
    build: ./frontend
    container_name: react_frontend
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres_flask:
    image: postgres:latest
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
