name: Security CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Frontend Docker image
        run: |
          docker build -t react_frontend ./frontend

      - name: Run Frontend container
        run: |
          docker run -d --name react_test -p 5173:5173 react_frontend
          sleep 10  # attendre que Vite démarre

      - name: Test Frontend with curl
        run: |
          curl -f http://localhost:5173 || exit 1

      - name: Stop Frontend container
        run: docker rm -f react_test

  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Backend Docker image
        run: |
          docker build -t flask_backend ./backend

      - name: Run Backend container
        run: |
          docker run -d --name flask_test -p 5000:5000 flask_backend
          sleep 10  # attendre que Flask démarre

      - name: Test Backend with curl
        run: |
          curl -f http://localhost:5000/api/test || exit 1

      - name: Stop Backend container
        run: docker rm -f flask_test
