name: Build and Test Docker

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        run: docker build -t react_frontend ./frontend

      - name: Test Frontend
        run: |
          docker run --rm -d -p 5173:5173 react_frontend
          sleep 10
          curl -f http://localhost:5173 || exit 1

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: docker build -t flask_backend ./backend

      - name: Test Backend
        run: |
          docker run --rm -d -p 5000:5000 flask_backend
          sleep 10
          curl -f http://localhost:5000/ || exit 1
